core/urls.py
from django.conf.urls import url
from neulyferreira.core import views


urlpatterns = [
    url(r'^$', views.home, name='home'),
]

neulyferreira/core/urls.py
from django.conf.urls import url
from neulyferreira.core import views


urlpatterns = [
    url(r'^', views.home, name='home'),
]

neulyferreira/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('neulyferreira.core.urls', namespace='core')),
    url(r'^admin/', admin.site.urls),
]

neulyferreira/categories/models.py
from django.db import models

class Category(models.Model):
    name = models.CharField('Nome', max_length=100)
    slug = models.SlugField('Atalho')
    created_at = models.DateTimeField(
        'Criado em', auto_now_add=True
    )
    updated_at = models.DateTimeField(
        'Atualizado em', auto_now=True
    )

neulyferreira/core/models.py
from django.db import models

# Create your models here.

neulyferreira/posts/models.py
from django.db import models

neulyferreira/categories/views.py
from django.shortcuts import render

# Create your views here.

neulyferreira/core/views.py
from django.shortcuts import render
from django.http import HttpResponse


def home(request):
    return render(request, 'home.html')

neulyferreira/posts/views.py
from django.shortcuts import render

# Create your views here.

neulyferreira/core/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1.0">
    <!--<link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon">
    <link rel="icon" href="images/favicon.ico" type="image/x-icon">-->
    <title> Neuly Ferreira | 2017 </title>
    <!-- Bootstrap css -->
    <link type="text/css" rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
    <!-- Owl Carousel css -->
    <link type="text/css" rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <!-- Font Awesome css -->
    <link type="text/css" rel="stylesheet" href="{% static 'css/font-awesome.css' %}">
    <!-- Magnific Popup css -->
    <link type="text/css" href="{% static 'css/magnific-popup.css' %}" rel="stylesheet" />
    <!-- Custom css -->
    <link type="text/css" href="{% static 'css/style.css' %}" rel="stylesheet" />
    <!-- Custom Media Query css -->
    <link type="text/css" href="{% static 'css/media.css' %}" rel="stylesheet" />
</head>
<body id="mainBox" data-spy="scroll" data-target="#main-menu" data-offset="150">
    <div class="blog-main">
        <div id="site-head">
            <!-- Header Section Begins -->
            <header id="header" class="header-block" data-top="0" data-scroll="100">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 main-menu">
                            <div class="menuBar scrollbtn">
                                <!-- Navigation Menu Begins -->
                                <nav class="navbar navbar-default">
                                    <div class="navbar-header">
                                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main-menu" aria-expanded="false">
                                            <span class="sr-only">Toggle navigation</span>
                                            <span class="icon-bar"></span>
                                            <span class="icon-bar"></span>
                                            <span class="icon-bar"></span>
                                        </button>
                                        <!-- Site Logo Begins -->
                                        <div class="logo">
                                            <a class="navbar-brand" href="index.html"><img src="images/logo.png" alt="logo" /></a>
                                        </div>
                                        <!-- Site Logo Ends -->
                                    </div>
                                    <div class="home-menu">
                                        <div class="collapse navbar-collapse" id="main-menu">
                                            <ul class="nav navbar-nav navbar-right">
                                                <li><a href="#banner">Quem sou?</a>
                                                </li>
                                                <li><a href="about.html">Posts</a></li>
                                                <li><a href="contact.html">Contato</a></li>
                                            </ul>
                                        </div>
                                        <!-- Search Form Begins -->
                                        <div class="search-form">
                                            <form>
                                                <div class="form-group">
                                                    <div class="btn-form"></div>
                                                    <input type="text" class="form-control" placeholder="Buscar">
                                                </div>
                                            </form>
                                        </div>
                                        <!-- Search Form Ends -->
                                    </div>
                                </nav>
                                <!-- Navigation Menu Ends -->
                            </div>
                        </div>
                    </div>
                </div>
            </header>
            <!-- Header Section Ends -->

        </div>
        <div class="main">
          <br /><br /><br /><br />
            <!-- Content Section Begins -->
            {% block content %}{% endblock %}
            <!-- Content Section Ends -->
            <!-- insta-post Section Begins -->
            <div id="insta-post" class="instagram-box pr pad-bottom-big">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                            <h2>Siga-me no <strong>Instagram..</strong></h2>
                        </div>
                    </div>
                </div>
                <div class="instagram-feed" id="footer-instagram-feed">
                    <div class="item">
                        <a href="javascript:void(0)"><img src="http://placehold.it/500x500" alt="Image"></a>
                    </div>
                    <div class="item">
                        <a href="javascript:void(0)"><img src="http://placehold.it/500x500" alt="Image"></a>
                    </div>
                    <div class="item">
                        <a href="javascript:void(0)"><img src="http://placehold.it/500x500" alt="Image"></a>
                    </div>
                    <div class="item">
                        <a href="javascript:void(0)"><img src="http://placehold.it/500x500" alt="Image"></a>
                    </div>
                    <div class="item">
                        <a href="javascript:void(0)"><img src="http://placehold.it/500x500" alt="Image"></a>
                    </div>
                    <div class="item">
                        <a href="javascript:void(0)"><img src="http://placehold.it/500x500" alt="Image"></a>
                    </div>
                    <div class="item">
                        <a href="javascript:void(0)"><img src="http://placehold.it/500x500" alt="Image"></a>
                    </div>
                    <div class="item">
                        <a href="javascript:void(0)"><img src="http://placehold.it/500x500" alt="Image"></a>
                    </div>
                    <div class="item">
                        <a href="javascript:void(0)"><img src="http://placehold.it/500x500" alt="Image"></a>
                    </div>
                    <div class="item">
                        <a href="javascript:void(0)"><img src="http://placehold.it/500x500" alt="Image"></a>
                    </div>
                    <div class="item">
                        <a href="javascript:void(0)"><img src="http://placehold.it/500x500" alt="Image"></a>
                    </div>
                    <div class="item">
                        <a href="javascript:void(0)"><img src="http://placehold.it/500x500" alt="Image"></a>
                    </div>
                    <div class="item">
                        <a href="javascript:void(0)"><img src="http://placehold.it/500x500" alt="Image"></a>
                    </div>
                </div>
            </div>
            <!-- insta-post Section Ends -->
            <!-- footer Section Begins -->
            <footer id="footer" class="footer pr pad-bottom-small text-align-center">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">

                            <!-- Subscribe Form Begins -->

                            <!-- Subscribe Form Ends -->
                            <!-- Footer Links Begins -->
                            <ul class="footer-links">
                                <li> <a href="javascript:void(0)">Início</a> </li>
                                <li> <a href="javascript:void(0)">Sobre</a> </li>
                                <li> <a href="javascript:void(0)">Posts</a> </li>
                                <li> <a href="javascript:void(0)">Contato</a> </li>
                            </ul>
                            <!-- Footer Links Ends -->
                            <!-- Social Media Links Begins -->
                            <ul class="social">
                                <li>
                                    <a href="javascript:void(0)"><i class="fa fa-facebook"></i></a>
                                </li>

                            </ul>
                            <!-- Social Media Links Ends -->
                        </div>
                    </div>
                </div>
            </footer>
            <!-- footer Section Ends -->
            <!-- Copyright Section Begins -->
            <div id="copyright" class="copyright pr text-align-center">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                            <h5>&copy; 2017 <a href="{% url 'core:home' %}">Neuly Ferreira</a> desenvolvido por <a href="https://arferreira.github.io/" class="dotstore-link" target="_blank">Antonio Ricardo.</a></h5>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Copyright Section Ends -->
            <!-- Back to top Section Begins -->
            <a href="javascript:void(0);" class="back-to-top"><i class="fa fa-long-arrow-up" aria-hidden="true"></i></a>
            <!-- Back to top Section Ends -->
        </div>
    </div>
    <!-- Mobile Menu Section Begins -->
    <div class="main_menucontent overlapblackbg"></div>
    <div class="menu-wrap"></div>
    <!-- Mobile Menu Section Ends -->
    <!-- Jquery Js -->
    <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
    <!-- Bootstrap Js -->
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- Modernizr Js -->
    <script type="text/javascript" src="{% static 'js/modernizr.js' %}"></script>
    <!-- Owl Carousel Js -->
    <script type="text/javascript" src="{% static 'js/owl.carousel.js' %}"></script>
    <!-- Localscroll Js -->
    <script type="text/javascript" src="{% static 'js/jquery.localscroll-1.2.7-min.js' %}"></script>
    <!-- Imagesloaded Js -->
    <script type="text/javascript" src="{% static 'js/imagesloaded.pkgd.min.js' %}"></script>
    <!-- Isotope Js -->
    <script type="text/javascript" src="{% static 'js/jquery.isotope.min.js' %}"></script>
    <!-- Parallax Js -->
    <script type="text/javascript" src="{% static 'js/jquery.parallax-1.1.3.js' %}"></script>
    <!-- Magnific Popup Js -->
    <script type="text/javascript" src="{% static 'js/jquery.magnific-popup.js' %}"></script>
    <!-- Custom Js -->
    <script type="text/javascript" src="{% static 'js/element.js' %}"></script>
</body>
</html>